'use client';
import { useState } from 'react';
import Link from 'next/link';

type Language='vi'|'en';
type Doc={id:number;title:string;titleEn:string|null;category:string;fileUrl:string;issuedAt:string|null;expiresAt:string|null};
type Log={id:number;summary:string;createdAt:string};
type PublicBatch={publicId:string;code:string;receivedAt:string|null;expiresAt:string|null};
type PublicProduct={id:number;name:string;batches:PublicBatch[]};
type Supplier={code:string;name:string;nameEn:string|null;productName:string|null;productNameEn:string|null;address:string|null;addressEn:string|null;taxCode:string|null;storage:string|null;storageEn:string|null;shelfLife:string|null;shelfLifeEn:string|null;notes:string|null;notesEn:string|null;status:string;verificationStatus:string;updatedAt:string;documents:Doc[];auditLogs:Log[];products:PublicProduct[]};

const legal=['BUSINESS_LICENSE','FOOD_SAFETY','CONTRACT','OTHER'];
const certificates=['TESTING','VIETGAP','HACCP','ISO'];
const categoryLabels={vi:{BUSINESS_LICENSE:'Đăng ký kinh doanh',FOOD_SAFETY:'An toàn thực phẩm',CONTRACT:'Hợp đồng',TESTING:'Phiếu kiểm nghiệm',VIETGAP:'VietGAP',HACCP:'HACCP',ISO:'ISO',OTHER:'Hồ sơ khác'},en:{BUSINESS_LICENSE:'Business registration',FOOD_SAFETY:'Food safety',CONTRACT:'Contract',TESTING:'Test report',VIETGAP:'VietGAP',HACCP:'HACCP',ISO:'ISO',OTHER:'Other document'}} as const;
const copy={
  vi:{tagline:'Minh bạch từ nguồn — An tâm mỗi bữa',verified:'✓ Đã xác minh',pending:'◷ Đang đối chiếu',system:'HỆ THỐNG TRUY XUẤT NGUỒN GỐC',productFallback:'Thông tin sản phẩm đang được đối chiếu',supplierCode:'Mã nhà cung cấp',supplier:'NHÀ CUNG CẤP',active:'Đang hợp tác',inactive:'Tạm ngừng công khai',tabs:['Nguồn gốc','Lô nhập hàng','Hồ sơ pháp lý','Chứng nhận','Cập nhật'],address:'Địa chỉ nhà cung cấp',tax:'Mã số thuế',storage:'Điều kiện bảo quản',shelfLife:'Hạn sử dụng',notes:'Ghi chú công khai',missing:'Chưa cập nhật',addressMissing:'Chưa có dữ liệu — cần đối chiếu hồ sơ nội bộ',shelfFallback:'Theo thông tin trên bao bì / hồ sơ sản phẩm',issued:'Cấp',expires:'Hết hạn',notRecorded:'Không ghi nhận',open:'Mở ↗',noDocs:'Chưa có hồ sơ công khai',legalEmpty:'Sunfood chưa công bố tệp pháp lý được phép lưu trữ cho nhà cung cấp này.',certEmpty:'Chứng nhận và phiếu kiểm nghiệm đang chờ được nhập hoặc đối chiếu.',historyFallback:'Thông tin nhà cung cấp được ghi nhận trong hệ thống Sunfood Tây Đô.',trust:'Cam kết minh bạch',trustText:'Thông tin do Sunfood Tây Đô quản lý và cập nhật. Hồ sơ chỉ được công khai khi có quyền lưu trữ và công bố.',translationNote:'Nội dung này đang hiển thị theo hồ sơ gốc tiếng Việt.'},
  en:{tagline:'Transparent sourcing — Confidence in every meal',verified:'✓ Verified',pending:'◷ Under review',system:'PRODUCT TRACEABILITY SYSTEM',productFallback:'Product information is under review',supplierCode:'Supplier code',supplier:'SUPPLIER',active:'Active supplier',inactive:'Public display paused',tabs:['Source','Inbound lots','Legal documents','Certificates','Updates'],address:'Supplier address',tax:'Tax identification number',storage:'Storage conditions',shelfLife:'Shelf life',notes:'Public notes',missing:'Not available',addressMissing:'No verified English data is available yet',shelfFallback:'Please refer to the product label or supporting documents',issued:'Issued',expires:'Expires',notRecorded:'Not recorded',open:'Open ↗',noDocs:'No public documents',legalEmpty:'Sunfood has not published any authorized legal documents for this supplier.',certEmpty:'Certificates and test reports are pending entry or verification.',historyFallback:'Supplier information was recorded in the Sunfood Tây Đô system.',trust:'Transparency commitment',trustText:'Information is managed and updated by Sunfood Tây Đô. Documents are published only when storage and disclosure are authorized.',translationNote:'This field is shown from the original Vietnamese record.'}
} as const;

function formatDate(value:string|null,lang:Language){return value?new Date(value).toLocaleDateString(lang==='vi'?'vi-VN':'en-GB'):copy[lang].notRecorded}
function localized(value:string|null,english:string|null,lang:Language,fallback:string){return lang==='en'?(english||value||fallback):(value||fallback)}

function DocumentList({documents,lang,empty}:{documents:Doc[];lang:Language;empty:string}){
  const t=copy[lang];
  return <div className="public-docs">{documents.length?documents.map(document=><a href={document.fileUrl} target="_blank" rel="noreferrer" className="public-doc" key={document.id}><span className="file-icon">▤</span><span><b>{lang==='en'?(document.titleEn||document.title):document.title}</b><small>{categoryLabels[lang][document.category as keyof typeof categoryLabels.vi]||document.category} · {t.issued}: {formatDate(document.issuedAt,lang)} · {t.expires}: {formatDate(document.expiresAt,lang)}</small></span><strong>{t.open}</strong></a>):<div className="empty-state"><span>◎</span><b>{t.noDocs}</b><p>{empty}</p></div>}</div>;
}

export default function PublicSupplier({supplier,aiEnabled}:{supplier:Supplier;aiEnabled:boolean}){
  const [tab,setTab]=useState('source'); const [lang,setLang]=useState<Language>('vi'); const t=copy[lang];
  const [question,setQuestion]=useState(''); const [aiBusy,setAiBusy]=useState(false); const [aiError,setAiError]=useState('');
  const [aiAnswer,setAiAnswer]=useState<{answer:string;sources:{id:string;label:string;href:string}[]}|null>(null);
  async function askAi(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!aiEnabled||!question.trim())return;setAiBusy(true);setAiError('');setAiAnswer(null);try{const response=await fetch('/api/ai/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:supplier.code,question,language:lang})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Trợ lý tạm thời không khả dụng.');setAiAnswer(result);}catch(error){setAiError(error instanceof Error?error.message:'Trợ lý tạm thời không khả dụng.');}finally{setAiBusy(false)}}
  const legalDocs=supplier.documents.filter(document=>legal.includes(document.category)); const certificateDocs=supplier.documents.filter(document=>certificates.includes(document.category)); const isVerified=supplier.verificationStatus==='VERIFIED';
  const product=localized(supplier.productName,supplier.productNameEn,lang,t.productFallback); const supplierName=localized(supplier.name,supplier.nameEn,lang,supplier.name); const address=localized(supplier.address,supplier.addressEn,lang,t.addressMissing); const storage=localized(supplier.storage,supplier.storageEn,lang,t.missing); const shelfLife=localized(supplier.shelfLife,supplier.shelfLifeEn,lang,t.shelfFallback); const notes=localized(supplier.notes,supplier.notesEn,lang,'');
  const tabKeys=['source','lots','legal','cert','history'];
  return <main className="trace-page"><header className="trace-header"><Link href="/" className="trace-logo"><span>SF</span><div><b>SUNFOOD TÂY ĐÔ</b><small>{t.tagline}</small></div></Link><div className="trace-header-actions"><div className="language-switch" aria-label="Language"><button className={lang==='vi'?'active':''} onClick={()=>setLang('vi')}>VI</button><button className={lang==='en'?'active':''} onClick={()=>setLang('en')}>EN</button></div><span className={isVerified?'verified':'verified pending'}>{isVerified?t.verified:t.pending}</span></div></header>
    <section className="trace-hero"><div className="hero-glow"/><div className="hero-content"><p>{t.system}</p><h1>{product}</h1>{lang==='en'&&!supplier.productNameEn&&supplier.productName&&<small className="translation-note">{t.translationNote}</small>}<div className="code-pill">{t.supplierCode} <b>{supplier.code}</b></div></div></section>
    <section className="trace-container"><div className="supplier-heading"><div className="supplier-avatar">{supplier.code.slice(-2)}</div><div><p>{t.supplier}</p><h2>{supplierName}</h2>{lang==='en'&&!supplier.nameEn&&<small className="translation-inline">{t.translationNote}</small>}<span className={supplier.status==='ACTIVE'?'active-dot':'inactive-dot'}>● {supplier.status==='ACTIVE'?t.active:t.inactive}</span></div></div>
      <nav className="public-tabs" aria-label="Traceability content">{tabKeys.map((key,index)=><button className={tab===key?'active':''} onClick={()=>setTab(key)} key={key}>{t.tabs[index]}</button>)}</nav>
      <div className="tab-content">{tab==='source'&&<div className="source-grid"><article><span>⌖</span><div><label>{t.address}</label><p>{address}</p>{lang==='en'&&!supplier.addressEn&&supplier.address&&<small className="field-note">{t.translationNote}</small>}</div></article><article><span>▣</span><div><label>{t.tax}</label><p>{supplier.taxCode||t.missing}</p></div></article><article><span>❄</span><div><label>{t.storage}</label><p>{storage}</p></div></article><article><span>◷</span><div><label>{t.shelfLife}</label><p>{shelfLife}</p></div></article>{notes&&<article className="wide"><span>i</span><div><label>{t.notes}</label><p>{notes}</p></div></article>}</div>}
        {tab==='lots'&&<div className="public-lots">{isVerified&&supplier.status==='ACTIVE'&&supplier.products.some(product=>product.batches.length)?supplier.products.flatMap(product=>product.batches.map(batch=><Link className="public-lot" href={`/lot/${batch.publicId}`} key={batch.publicId}><span><b>{product.name}</b><small>{lang==='vi'?'Mã lô':'Lot code'}: {batch.code} · {lang==='vi'?'Ngày nhập':'Received'}: {formatDate(batch.receivedAt,lang)}</small></span><strong>{lang==='vi'?'Xem lô →':'View lot →'}</strong></Link>)):<div className="empty-state"><span>▣</span><b>{lang==='vi'?'Chưa có lô được công bố':'No published lots'}</b><p>{lang==='vi'?'Lô nhập hàng chỉ xuất hiện sau khi thông tin và nhà cung cấp được xác minh.':'Inbound lots appear after the supplier and lot data are verified.'}</p></div>}</div>}
        {tab==='legal'&&<DocumentList documents={legalDocs} lang={lang} empty={t.legalEmpty}/>} {tab==='cert'&&<DocumentList documents={certificateDocs} lang={lang} empty={t.certEmpty}/>} {tab==='history'&&<div className="timeline">{supplier.auditLogs.length?supplier.auditLogs.map(log=><div key={log.id}><span/><article><time>{new Date(log.createdAt).toLocaleString(lang==='vi'?'vi-VN':'en-GB')}</time><p>{lang==='vi'?log.summary:t.historyFallback}</p></article></div>):<div><span/><article><time>{formatDate(supplier.updatedAt,lang)}</time><p>{t.historyFallback}</p></article></div>}</div>}
      </div><section className="trace-ai"><div><b>{lang==='vi'?'Hỏi về nguồn gốc':'Ask about this source'}</b><p>{aiEnabled?(lang==='vi'?'Trợ lý chỉ dùng dữ liệu nhà cung cấp đã xác minh và hồ sơ công khai.':'Answers use only verified supplier data and public document metadata.'):(lang==='vi'?'Trợ lý sẽ mở khi dữ liệu nhà cung cấp được xác minh và hệ thống AI được cấu hình.':'The assistant will open after supplier verification and AI setup.')}</p></div>{aiEnabled&&<form onSubmit={askAi}><input value={question} onChange={event=>setQuestion(event.target.value)} maxLength={300} placeholder={lang==='vi'?'Ví dụ: Nhà cung cấp này có hồ sơ gì?':'For example: Which documents are available?'} aria-label={lang==='vi'?'Câu hỏi về nguồn gốc':'Traceability question'} required/><button disabled={aiBusy}>{aiBusy?'…':lang==='vi'?'Hỏi AI':'Ask AI'}</button></form>}{aiError&&<p role="alert">{aiError}</p>}{aiAnswer&&<div className="trace-ai-answer"><p>{aiAnswer.answer}</p>{aiAnswer.sources.length>0&&<div>{aiAnswer.sources.map(source=><a key={source.id} href={source.href} target={source.id==='supplier'?undefined:'_blank'} rel="noreferrer">{source.label} ↗</a>)}</div>}</div>}<small>{lang==='vi'?'AI không xác nhận tính thật của giấy tờ hoặc độ an toàn của sản phẩm.':'AI does not certify documents or food safety.'}</small></section><div className="trust-note"><span>✓</span><p><b>{t.trust}</b><br/>{t.trustText}</p></div>
    </section><footer className="trace-footer"><b>CÔNG TY CỔ PHẦN THỰC PHẨM SUNFOOD TÂY ĐÔ</b><p>{lang==='vi'?'MST 0110716043 · Số 17-19 Khu TT Cầu 1, đường Phan Bá Vành, phường Đông Ngạc, TP Hà Nội':'Tax ID 0110716043 · No. 17-19 Cau 1 Collective Area, Phan Ba Vanh Street, Dong Ngac Ward, Hanoi, Vietnam'}</p><p>tpsunfoodtaydoo@gmail.com · www.sunfoodtaydo.com</p></footer>
  </main>;
}
